[tool.poetry]
name = "stories-jax"
version = "0.1.0"
description = "Learn spatially informed Waddington-like potentials for single-cell gene expression"
authors = ["Geert-Jan Huizing <gjhuizing@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
anndata = "^0.10.7"
jaxlib = {version = "0.4.25+cuda11.cudnn86", source = "jax"}
jax = {version = "0.4.25", extras = ["cuda11_pip"]}
optax = "^0.2.2"
flax = "^0.8.2"
jaxopt = "^0.8.3"
numpy = "^1.26.4"
tqdm = "^4.66.2"
orbax-checkpoint = "^0.5.9"
ott-jax = "^0.4.5"
ipykernel = "^6.29.4"
scanpy = "^1.10.1"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"


[[tool.poetry.source]]
name = "jax"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
priority = "primary"


[tool.poetry.group.dev.dependencies]
hydra-core = "^1.3.2"
wandb = "^0.16.6"
flatten-dict = "^0.4.2"
seaborn = "^0.13.2"
matplotlib = "^3.8.4"
einops = "^0.7.0"
hydra-submitit-launcher = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
